CREATE OR REPLACE TABLE ATTRIBUTES.DATES (
   DATE             DATE        NOT NULL
  ,YEAR             SMALLINT    NOT NULL
  ,MONTH            SMALLINT    NOT NULL
  ,MONTH_NAME       CHAR(3)     NOT NULL
  ,DAY_OF_MON       SMALLINT    NOT NULL
  ,DAY_OF_WEEK      VARCHAR(9)  NOT NULL
  ,WEEK_OF_YEAR     SMALLINT    NOT NULL
  ,DAY_OF_YEAR      SMALLINT    NOT NULL
)
AS
  WITH CTE_DATE AS (
    SELECT DATEADD(DAY, SEQ4(), '2010-01-01') AS DATE
      FROM TABLE(GENERATOR(ROWCOUNT=>5000))  
-- Number of days after reference date in previous line
  )
  SELECT DATE
        ,YEAR(DATE)
        ,MONTH(DATE)
        ,MONTHNAME(DATE)
        ,DAY(DATE)
        ,DAYOFWEEK(DATE)
        ,WEEKOFYEAR(DATE)
        ,DAYOFYEAR(DATE)
    FROM CTE_DATE
;